spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  config:
    import: configserver:http://configserver:8071/
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true